### PR TITLE
proposed fix for debug flag

### PR DESCRIPTION
**Pull request by johnnagro**
#22

### CODE REVIEW

**Comment by samknight** [comment]
👍

**Comment by maxehmookau** [comment]
Thank you for this! 

I like this but I'm wondering If maybe we switch the logic round so that the default is to use the test API since the live one is quite aggressively rate limited.

Thoughts @samknight ?

**Comment by samknight** [comment]
I think default should still be live. I don't see much benefit in the test server since a self signed certificate then uploads onto a site which may already be live. Debug to me should be more verbose output rather than test servers.

This was something I was going to discuss at a later point. But for those reasons I think default should be live.

**Comment by maxehmookau** [comment]
Yeah,  that's a fair point. I’ll merge this then!

**Pull request merged**
