### PR TITLE
Add travis.yml

### PR DESCRIPTION
**Pull request by CGA1123**
#4 mentions wanting to add the repo to travis

Travis CI currently [does not support ruby 2.3](https://docs.travis-ci.com/user/languages/ruby#Supported-Ruby-Versions-and-RVM)

### CODE REVIEW

**Comment by maxehmookau** [comment]
Hi @CGA1123, thanks so much for the PR.

Just a few notes from me:

1. Your `.travis.yml` file needs to be in the root directory. At the moment, Travis can't find it as it's in the `workers` directory.
1. I know that Travis doesn't currently support 2.3 but I assume it's only a matter of time until it does. I'm not keen on the idea of regressing the code in terms of Ruby version to make it fit a particular CI solution. I would recommend leaving the version as 2.3 and then keeping this PR open until Travis does support 2.3 at which point I'll merge.

Does that all seem fair?

**Comment by CGA1123** [comment]
Hey @maxehmookau,

Sounds good to me!

**Comment by CGA1123** [comment]
Just noticed, looking at the travis build log, it seems that ruby 2.3.1 is actually supported.

rake not being part of the bundle is the reason for the failure.

**Comment by maxehmookau** [comment]
Great, looking good.

To fix that error, I think just adding `rake` to the gemfile and adding a `Rakefile` should at least make travis pass even if there's no actual test yet.

**Comment by CGA1123** [comment]
What testing framework are you looking at using?
Just so that a default rake task can be set to run the framework, even if no tests are present.

**Comment by maxehmookau** [comment]
Ideally minitest. Since it's fairly simple to pick up unlike rspec which has a bit of a learning curve.

I'll merge this now though since the build technically passes (even though it's not checking anything). Feel free to submit a PR if you want to add minitest, otherwise I'll do it when I get a spare moment :)

Thanks! 👍

**Pull request merged**
